"""Machine-readable provenance registry for WindFusion v0.2.

Every concept that WindFusion reuses from an upstream repository owned by
``rajaram-2005`` is declared here with its upstream path, upstream licence and
the *kind* of reuse.  Nothing in this repository is copied verbatim from an
upstream tree: entries marked ``concept`` were re-implemented from first
principles after reading the upstream source, and entries marked ``equation``
re-derive published physical relations that predate (and are not owned by) any
of the upstream repositories.

The registry is consumed by:

* ``windfusion provenance`` (CLI) and :func:`provenance_table`,
* ``docs/PROVENANCE.md`` (generated by ``python -m windfusion provenance --markdown``),
* the audit test ``tests/test_provenance.py``, which fails if a module claims a
  lineage it does not declare.

Reuse kinds
-----------
``concept``   Idea/strategy re-implemented independently in this repository.
``equation``  Published physical relation (Heier Cp, ISO 281, Jensen wake, ...)
              re-derived here; upstream only supplied the choice of relation.
``schema``    Naming/structural convention adopted for interoperability.
``protocol``  Evaluation or training protocol reproduced so numbers are
              comparable across the repositories.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Concept:
    """One reused idea and where it came from."""

    concept_id: str
    source_repo: str
    upstream_path: str
    upstream_license: str
    reuse: str
    local_path: str
    description: str
    validated_by: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""

    def as_row(self) -> str:
        validated = ", ".join(self.validated_by) if self.validated_by else "not yet validated"
        return (
            f"| `{self.concept_id}` | {self.source_repo} | `{self.upstream_path}` | "
            f"{self.upstream_license} | {self.reuse} | `{self.local_path}` | {validated} |"
        )


MIT = "MIT"
NO_LICENSE = "no licence file"

PROVENANCE: tuple[Concept, ...] = (
    # ── wind-turbine-pg-bnn: uncertainty ────────────────────────────────────
    Concept(
        concept_id="heteroscedastic_nll",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="model.py::PhysicsGuidedBNN.elbo_loss",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/training/losses.py",
        description=(
            "Gaussian negative log-likelihood with a learned observation-noise "
            "(log-variance) head, used as the predictive-loss term."
        ),
        validated_by=("tests/test_training.py", "benchmarks/synthetic_benchmark.py"),
    ),
    Concept(
        concept_id="aleatoric_epistemic_split",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/aerovigil_pg_bnn/model.py (MC sampling)",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/models/uncertainty.py",
        description=(
            "Split predictive variance into aleatoric (learned noise) and "
            "epistemic (MC-dropout spread) parts. Bayes-by-backprop weight "
            "uncertainty is replaced by MC dropout for edge cost; this is an "
            "approximation, not variational inference."
        ),
        validated_by=("tests/test_uncertainty.py",),
        notes="Approximate posterior; see model card for the calibration caveat.",
    ),
    # ── wind-turbine-pg-bnn: physics ────────────────────────────────────────
    Concept(
        concept_id="heier_cp_betz",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/physics/aerodynamics.py::power_coefficient",
        upstream_license=MIT,
        reuse="equation",
        local_path="windfusion/physics/aerodynamics.py",
        description=(
            "Heier Cp(beta, lambda) empirical approximation clamped to the Betz "
            "limit 16/27, plus P = 0.5*rho*A*v^3*Cp."
        ),
        validated_by=("tests/test_physics.py",),
        notes="Heier (1998) / Betz (1919): published relations, not upstream IP.",
    ),
    Concept(
        concept_id="jensen_wake",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/physics/aerodynamics.py::jensen_wake_deficit",
        upstream_license=MIT,
        reuse="equation",
        local_path="windfusion/physics/aerodynamics.py",
        description=(
            "Jensen/Park wake deficit used by the Qinglong (fleet/wake) "
            "architecture to condition on upstream neighbours."
        ),
        validated_by=("tests/test_physics.py",),
        notes="Jensen (1983), Risø-M-2411.",
    ),
    Concept(
        concept_id="iso281_l10",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/physics/drivetrain.py::bearing_l10_life_hours, src/physics/constraints.py::iso_281_l10_hours",
        upstream_license=MIT,
        reuse="equation",
        local_path="windfusion/physics/drivetrain.py",
        description=(
            "ISO 281 L10 rating life (C/P)^p and the cubic/10-3 load-life "
            "exponent, used as the damage-rate prior for the Odin drivetrain "
            "preset and the synthetic-fleet damage model."
        ),
        validated_by=("tests/test_physics.py",),
    ),
    Concept(
        concept_id="lumped_thermal_rc",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/physics/thermal.py::winding_temperature_derivative",
        upstream_license=MIT,
        reuse="equation",
        local_path="windfusion/physics/thermal.py",
        description=(
            "First-order lumped RC winding/coolant model, integrated "
            "semi-analytically for stability at long time steps."
        ),
        validated_by=("tests/test_physics.py",),
    ),
    Concept(
        concept_id="soft_hinge_limits",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/physics/constraints.py::_soft_relu_penalty",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/physics/constraints.py",
        description=(
            "Differentiable soft-hinge penalty that keeps predictions inside "
            "documented (non-OEM) operating limits."
        ),
        validated_by=("tests/test_physics.py",),
        notes="Limits are research defaults, explicitly NOT OEM limits.",
    ),
    # ── wind-turbine-pg-bnn: evaluation protocol ────────────────────────────
    Concept(
        concept_id="ece_coverage",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/eval/calibration.py::expected_calibration_error",
        upstream_license=MIT,
        reuse="protocol",
        local_path="windfusion/evaluation/metrics.py",
        description=(
            "Expected calibration error over central predictive intervals, "
            "re-implemented without SciPy so it works on the edge path."
        ),
        validated_by=("tests/test_metrics.py",),
    ),
    Concept(
        concept_id="early_warning_lead_time",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/eval/calibration.py::early_warning_metrics, first_warning_lead_time_days",
        upstream_license=MIT,
        reuse="protocol",
        local_path="windfusion/evaluation/metrics.py",
        description=(
            "Fixed-horizon early-warning metrics (precision/recall/F1, false "
            "alarm rate, mean lead time in days) at a configurable horizon."
        ),
        validated_by=("tests/test_metrics.py",),
    ),
    Concept(
        concept_id="fault_taxonomy_vocabulary",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/faults/taxonomy.py, src/faults/limits.py",
        upstream_license=MIT,
        reuse="schema",
        local_path="windfusion/data/schema.py",
        description=(
            "Subsystem/fault-mode vocabulary and severity ordering adopted so "
            "labels, telemetry and reports interoperate across the repositories."
        ),
        validated_by=("tests/test_synthetic.py",),
    ),
    # ── wind-turbine-pg-bnn: deployment ─────────────────────────────────────
    Concept(
        concept_id="onnx_export_contract",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/deployment/export_onnx.py",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/deployment/export.py",
        description=(
            "ONNX export with named dynamic axes, optional dynamic "
            "quantisation, and a mandatory numerical-parity check against "
            "ONNX Runtime before an artefact is accepted."
        ),
        validated_by=("tests/test_export.py",),
    ),
    # ── AeroZip: telemetry ──────────────────────────────────────────────────
    Concept(
        concept_id="anomaly_bypass_telemetry",
        source_repo="AeroZip-Telemetry-Compression",
        upstream_path="AeroZipSimulator.java",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/edge/telemetry.py",
        description=(
            "Compression is bypassed and raw payloads are emitted whenever an "
            "anomaly/risk signal crosses a threshold. Generalised from a fixed "
            "score threshold to a multi-signal risk policy."
        ),
        validated_by=("tests/test_telemetry.py",),
        notes="The Java codec is not vendored; the policy is re-implemented in NumPy.",
    ),
    Concept(
        concept_id="delta_deadband_quant_codec",
        source_repo="AeroZip-Telemetry-Compression",
        upstream_path="AeroZipSimulator.java (delta + deadband + quantise)",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/edge/telemetry.py",
        description=(
            "Delta coding, deadband suppression and fixed-point quantisation "
            "re-implemented so compression ratio and reconstruction fidelity "
            "can be measured in this repository."
        ),
        validated_by=("tests/test_telemetry.py",),
    ),
    # ── TurbineDigitalTwin: state semantics ─────────────────────────────────
    Concept(
        concept_id="twin_state_vocabulary",
        source_repo="TurbineDigitalTwin",
        upstream_path="app.py",
        upstream_license=NO_LICENSE,
        reuse="schema",
        local_path="windfusion/digital_twin/state.py",
        description=(
            "Typed turbine-state vocabulary and what-if scenario semantics. "
            "The upstream dashboard-coupled Random Forest is not reused; the "
            "state is driven by the learned model plus accumulated damage."
        ),
        validated_by=("tests/test_digital_twin.py",),
        notes="Upstream ships no licence file and a committed .env; neither is copied.",
    ),
    # ── ai-machinery-etl-pipeline: data zones ───────────────────────────────
    Concept(
        concept_id="data_zone_layout",
        source_repo="ai-machinery-etl-pipeline",
        upstream_path="README.md (n8n/Ollama/Supabase/Langflow orchestration)",
        upstream_license=MIT,
        reuse="schema",
        local_path="data/{raw,processed,features,synthetic,validation,benchmarks}",
        description=(
            "Raw / processed / feature / synthetic / validation / benchmark "
            "zone separation with checksum and split provenance recorded per "
            "artefact. The Docker/n8n stack is not a dependency."
        ),
        validated_by=("tests/test_dataset.py",),
    ),
    # ── wind-turbine-pg-bnn: fleet learning ─────────────────────────────────
    Concept(
        concept_id="federated_physics_weighted_average",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/federated/fed_client.py, configs/default.yaml::federated.physics_aware_aggregation",
        upstream_license=MIT,
        reuse="protocol",
        local_path="windfusion/training/fleet.py",
        description=(
            "FedAvg over per-site clients with aggregation weights that reward "
            "low physics residual; re-implemented locally (no Flower runtime)."
        ),
        validated_by=("tests/test_fleet.py",),
    ),
    Concept(
        concept_id="reptile_site_adaptation",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/meta/reptile.py, src/meta/tasks.py",
        upstream_license=MIT,
        reuse="protocol",
        local_path="windfusion/training/fleet.py",
        description=(
            "First-order Reptile meta-learning across site-tasks so a new farm "
            "adapts from a handful of labelled windows."
        ),
        validated_by=("tests/test_fleet.py",),
    ),
    Concept(
        concept_id="onboarding_confidence_gates",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="src/agents/hermes.py",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/training/onboarding.py",
        description=(
            "Self-training onboarding that only accepts pseudo-labels below an "
            "uncertainty gate and promotes a site model only if held-out gates "
            "pass. Re-implemented with an explicit audit trail."
        ),
        validated_by=("tests/test_onboarding.py",),
    ),
    # ── safety ──────────────────────────────────────────────────────────────
    Concept(
        concept_id="advisory_only_safety",
        source_repo="wind-turbine-pg-bnn",
        upstream_path="configs/default.yaml::safety (advisory_only, allow_actuation: false)",
        upstream_license=MIT,
        reuse="concept",
        local_path="windfusion/config.py::SafetyConfig, docs/SAFETY.md",
        description=(
            "Advisory-only operation with actuation disabled is carried over as "
            "a hard invariant enforced by tests, not a documentation note."
        ),
        validated_by=("tests/test_safety.py",),
    ),
)

PROVENANCE_BY_ID: dict[str, Concept] = {c.concept_id: c for c in PROVENANCE}

REUSE_KINDS = ("concept", "equation", "schema", "protocol")


def provenance_table() -> str:
    """Markdown table of every declared reused concept."""
    header = (
        "| Concept | Source repository | Upstream path | Licence | Reuse | Local path | Validated by |\n"
        "|---|---|---|---|---|---|---|"
    )
    return "\n".join([header, *[c.as_row() for c in PROVENANCE]])


def provenance_markdown() -> str:
    """Full provenance document body (used to generate docs/PROVENANCE.md)."""
    counts: dict[str, int] = {}
    for c in PROVENANCE:
        counts[c.reuse] = counts.get(c.reuse, 0) + 1
    by_repo: dict[str, int] = {}
    for c in PROVENANCE:
        by_repo[c.source_repo] = by_repo.get(c.source_repo, 0) + 1
    summary = "\n".join(f"- **{repo}** — {n} reused concepts" for repo, n in sorted(by_repo.items()))
    kinds = "\n".join(f"- `{k}` — {counts.get(k, 0)}" for k in REUSE_KINDS)
    unvalidated = [c.concept_id for c in PROVENANCE if not c.validated_by]
    gap = (
        "Every declared concept is covered by at least one test."
        if not unvalidated
        else "Declared but not yet covered by a test: " + ", ".join(unvalidated)
    )
    return (
        "# Provenance registry\n\n"
        "Generated by `python -m windfusion provenance --markdown`. Do not edit "
        "by hand; edit `windfusion/provenance.py` instead.\n\n"
        "No upstream source tree was copied into this repository. `concept` "
        "entries were re-implemented after reading the upstream code; `equation` "
        "entries are published physical relations that predate the upstream "
        "repositories.\n\n"
        f"## Sources\n\n{summary}\n\n## Reuse kinds\n\n{kinds}\n\n"
        f"## Registry\n\n{provenance_table()}\n\n## Validation gap\n\n{gap}\n"
    )


def validate_provenance() -> list[str]:
    """Return a list of problems (empty list means the registry is consistent)."""
    problems = []
    seen = set()
    for c in PROVENANCE:
        if c.concept_id in seen:
            problems.append(f"duplicate concept id {c.concept_id}")
        seen.add(c.concept_id)
        if c.reuse not in REUSE_KINDS:
            problems.append(f"{c.concept_id}: unknown reuse kind {c.reuse!r}")
        if not c.source_repo:
            problems.append(f"{c.concept_id}: missing source repository")
        if not c.local_path:
            problems.append(f"{c.concept_id}: missing local path")
    return problems
